apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec:
      containers:
      - name: sentiment-analysis
        image: sentiment-analysis  # Replace with your image name (optional)
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: model-volume
          mountPath: /app/model
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: sentiment-analysis-pvc
