apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "hotdog-sample"
spec:
  predictor:
    model:
      modelFormat:
        name: tensorflow
      storageUri: "https://github.com/nirmesh/tf-classifier"
